server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewservice
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


#  sql:
#    init:
#      mode: always
#      data-locations: classpath:import.sql